services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    ports: 
      - 2345:5432
    env_file: 
      - back-end/.env
    volumes:
      - db:/var/lib/postgresql/data
  
  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env
    
  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html
  
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - node_app
      - react_app
  
volumes:
  db:
  build_react:
    