name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Mark back-end env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: postgres
          envkey_POSTGRES_PASSWORD: postgres
          envkey_POSTGRES_DB: students_test
          envkey_DATABASE_URL: postgresql://postgres:postgres@db:5432/students_test
          file_name: back-end/.env
      - name: Mark front-end env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_BASE_URL: http://ec2-18-204-215-139.compute-1.amazonaws.com/api
          file_name: front-end/.env
      - name: build
        run: docker-compose down -v && docker-compose build
      - name: run
        run: docker-compose up -d


      
